// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Sub-Atomica",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Sub-Atomica",
            targets: ["AppModule"],
            bundleIdentifier: "anshulkumaria1612-gmail.com.Sub-Atomica",
            teamIdentifier: "G3Y27UPJJ3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "AR View."),
                .photoLibrary(purposeString: "Photos access."),
                .photoLibraryAdd(purposeString: "Photo saving.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)